services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./deploy/api/Dockerfile
    ports:
      - "4000:4000"
    restart: always
  
  app:
    container_name: app
    build:
      context: ./web
      dockerfile: ../deploy/app/Dockerfile
    ports:
      - "5000:80"
    restart: always
