-- Reverse Migration Script

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE;

USE `mydb`;

-- Drop tables in reverse order of dependency
DROP TABLE IF EXISTS `tokens`;
DROP TABLE IF EXISTS `user_tags`;
DROP TABLE IF EXISTS `tags`;
DROP TABLE IF EXISTS `user_stores`;
DROP TABLE IF EXISTS `stores`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `blacklist`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
